---
- name: Initialize the disk and allocate the space
  hosts: all
  tasks:
    - name: Initialize a disk
      community.windows.win_initialize_disk:
        disk_number: 2
        force: yes

    - name: Get disk facts
      win_disk_facts:

    - name: Output allocated disk size
      debug:
        var: ansible_facts.disks[2].size

    - name: Create a partition with drive letter D and size 5 GiB
      community.windows.win_partition:
        drive_letter: E
        partition_size: -1
        disk_number: 2
