---
- name: Initialize the disk and allocate the space
  hosts: all
  tasks:
    - name: Initialize a disk
      community.windows.win_initialize_disk:
        disk_number: 2
        force: yes

    - name: Get disk facts
      win_disk_facts:

    - name: Output first disk size
      debug:
        var: ansible_facts.disks[2].size
